checks:
    python:
        code_rating: true
        duplicate_code: true
build:
  nodes:
    analysis:
      tests:
        override:
          - py-scrutinizer-run
          - pylint-run fast_tornado
          - command: export PYTHONPATH='.' && pytest testcases --cov fast_tornado --cov-report xml
            coverage:
                file: .coverage
                format: 'py-cc'
